org: 200millas
service: my-multi-service-project

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  memorySize: 256
  timeout: 20

services:
  resources:
    path: resources
  employees:
    path: employees
    dependsOn:
      - service-resources
  users:
    path: users
    dependsOn:
      - service-resources
  products:
    path: products
    dependsOn:
      - service-resources
